name: residential
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_riverpod: ^2.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  font_awesome_flutter: ^10.4.0
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  flutter_typeahead: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  freezed: ^2.3.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
